name: Deploy Pages (web)
on:
  push:
    branches: [ "main" ]
    paths:
      - "web/**"
      - ".github/workflows/deploy-pages.yml"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with: { path: "./web" }
      - id: deployment
        uses: actions/deploy-pages@v4
