name = "goldsignalsx-worker"
main = "worker.js"
compatibility_date = "2024-10-01"

[vars]
UPSTREAM_URL = "https://gold-ticks.example.workers.dev/price"
ALLOW_ORIGINS = '["*"]'
RL_LIMIT = "180"

[[kv_namespaces]]
binding = "GSX_KV"
id = "YOUR_KV_NAMESPACE_ID"

[[d1_databases]]
binding = "GSX_DB"
database_name = "gsx_db"
database_id = "YOUR_D1_ID"

[triggers]
crons = ["*/5 * * * *"]
